AllocaInst class
glu-lang/glu pull request #148
Opened 2024-12-02 10:01 UTC by badermarouan

Fix #35

2024-12-03 19:21 UTC, Snowy1803 commented on include/GIL/Instructions/AllocaInst.hpp
> +class AllocaInst : public InstBase {
you are not implementing any of the abstract methods

2024-12-03 19:21 UTC, Snowy1803 commented on include/GIL/Instructions/AllocaInst.hpp
> +    size_t size; ///< The size of the allocation.
there is no size, only a type (the Type type already stores the size anyway)

2025-01-30 12:09 UTC, Snowy1803 commented on include/GIL/Instructions/AllocaInst.hpp
> +    AllocaInst(size_t size, Type type)
no size

2025-02-04 03:50 UTC, Snowy1803 requested changes

2025-02-04 03:50 UTC, Snowy1803 commented on include/GIL/Type.hpp
> +    }
1- you cannot call `new` to create a type, we'll use an arena, so that would break pointer equality rules, and it would never be freed
2 -  the size/alignment of a pointer is not the same as the pointee
3 - why would a fake copy constructor create a pointer type instead of a copy??
4 - this is never called so it doesn't even resolve the problem

2025-02-04 11:10 UTC, badermarouan commented on include/GIL/Type.hpp
> +    }
This is still work in progress/in discussion that's why I didn't ask for a new review

2025-03-06 22:03 UTC, Snowy1803 commented on include/GIL/Instructions.hpp
> +#include "Instructions/AllocaInst.hpp"
clang format

2025-03-06 22:03 UTC, Snowy1803 commented on include/GIL/Instructions/AllocaInst.hpp
> +    AllocaInst(Type type, TypeMemory *astTypeMemory)
Take the context

2025-03-06 22:03 UTC, Snowy1803 commented on include/GIL/Instructions/AllocaInst.hpp
> +        , _typeMemory(astTypeMemory)
Don’t store it, it’s not used

2025-03-09 00:12 UTC, Snowy1803 commented on include/GIL/Instructions/AllocaInst.hpp
> +        , _typeMemory(astTypeMemory)
still, don't store the context, you don't use it.

2025-03-09 00:14 UTC, Snowy1803 commented on include/GIL/Instructions/AllocaInst.hpp
> +        return Operand(_ptr);
the operand is the pointee type, not the pointer type (we allocate a value, not a pointer)

2025-03-09 00:14 UTC, Snowy1803 commented on include/GIL/Instructions/AllocaInst.hpp
> +    Context *_context; ///< The AST Context.
don't store the context, it has nothing to do here

2025-03-11 18:34 UTC, Snowy1803 approved these changes

2025-03-11 22:12 UTC, merged